version: '3'

services:
        db_hypertube:
            image: postgres
            environment:
                - POSTGRES_DB=hypertube
                - POSTGRES_USER=mcomet
                - POSTGRES_PASSWORD=pass_mcomet
            restart: always
            volumes:
                - 'pgdata:/var/lib/postgresql/data'
            container_name: db_hypertube

        web:
            build: .
            command: python manage.py runserver 0.0.0.0:8000
            volumes:
                - '.:/code'
            ports:
                -  "8000:8000"
            depends_on:
                - db_hypertube
            restart: always
            container_name: web

        adminer:
            container_name: adminer
            image: adminer
            restart: always
            ports:
                - 8081:8080
            depends_on:
                - db_hypertube
volumes:
        pgdata:
            external: true
