version: '3'

services:
        db:
            image: postgres
            environment:
                - POSTGRES_DB=hypertube
                - POSTGRES_USER=mcomet
                - POSTGRES_PASSWORD=pass_mcomet
            restart: always
            container_name: db

        web:
            build: .
            command: python manage.py runserver 0.0.0.0:8000
            volumes:
                - '/root/jenkins_home/workspace/Hypertube:/code'
            ports:
                -  "8000:8000"
            depends_on:
                - db
            restart: always
            container_name: web

        adminer:
            container_name: adminer
            image: adminer
            restart: always
            ports:
                - 8081:8080
            depends_on:
                - db

        jenkins:
            container_name: jenkins
            restart: always
            ports:
                - '8080:8080'
                - '50000:50000'
            volumes:
                - '/var/run/docker.sock:/var/run/docker.sock'
                - '/usr/bin/docker:/usr/bin/docker'
                - '/usr/local/bin/docker-compose:/usr/local/bin/docker-compose'
                - '/root/jenkins_home:/var/jenkins_home'
                - '/root/backups:/var/backups'
            image: 'jenkins/jenkins:lts'
            user: root
            environment:
                - TZ="Europe/Moscow"

        apache:
            container_name: apache-template
            restart: always
            ports:
                - '1111:80'
            volumes:
                - './vidoe_template:/usr/local/apache2/htdocs/'
            image: 'httpd:2.4'
